include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    avoid_slow_async_io: ignore
  plugins:
    - custom_lint

linter:
  rules:
    public_member_api_docs: false
    flutter_style_todos: false
    comment_references: false
    avoid_setters_without_getters: false
    lines_longer_than_80_chars: false
    one_member_abstracts: false
    use_build_context_synchronously: true
