name: ice

packages:
  - ./
  - packages/**

ignore:
  - "packages/**/example"
  - "packages/ion_screenshot_detector"

command:
  bootstrap:
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    runPubGetInParallel: false
    usePubspecOverrides: true

scripts:
  pub_get:
    exec: asdf exec flutter pub get
  analyze:
    exec: asdf exec flutter analyze && asdf exec dart run custom_lint
  test:
    exec: asdf exec flutter test
  build_runner:
    exec: asdf exec flutter pub run build_runner build --delete-conflicting-outputs
    concurrency: 4
  build_runner_watch:
    exec: asdf exec flutter pub run build_runner watch --delete-conflicting-outputs
  generate_code:
    run: ./scripts/generate_code.sh
  generate_locales:
    run: ./scripts/generate_locales.sh
  generate:
    run: |
      melos run generate_code
      melos run generate_locales
  4mat:
    run: ./scripts/format_code.sh
